version: '3.3'

services:
    db:
        build: ./mysqlImage/
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        ports:
            - "3360:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes:
        - ./mysql:/var/lib/mysql
        networks: 
            - database
        container_name: mysql_db
    
    adminer:
        image: adminer
        restart: on-failure
        ports:
            - "9030:9030"
        networks: 
            - database

    nodejs:
        build: ./apiNodejs/
        volumes: 
            - ./apiNodejs/:/user/src/app
        ports:
            - '3000:3000'
            - '3001:3360'
        networks: 
            - database
        restart: on-failure

networks:
    database:
        driver: bridge